### ISSUE TITLE
Signing `wss` scheme returns `https` anyway

### ISSUE THREAD

**Issue by MohammedNoureldin** [jakub-bacic/aws_auth#5]
When signing a URL with a scheme other than `https` (which is hard-coded now), the result signed URL should be with the original scheme, and not be replaced by https anyway. Example:

signing:

    wss://abc123.execute-api.eu-central-1.amazonaws.com/dev'

should return:

    wss://abc123.execute-api.eu-central-1.amazonaws.com/dev?X-......'
      ^
and NOT:

    https://abc123.execute-api.eu-central-1.amazonaws.com/dev?X-......'
      ^
Could you take care of that please?

**Comment by jakub-bacic** [comment]
@MohammedNoureldin 
Could you verify that the version from #6 works for you?

You can use test in your project by temporarily specifying dependency as git reference in `pubspec.yaml`:
```
dependencies:
  aws_auth:
    git:
      url: git@github.com:jakub-bacic/aws_auth.git
      ref: fe1ff94
```

I'll release it once it's merged to master branch.

**Comment by MohammedNoureldin** [comment]
Works perfectly! Thank you!

Just a small correction for the syntax to use a specific version from Git repo:

```
  aws_auth:
    git:
      url: git://github.com/jakub-bacic/aws_auth.git
      ref: fe1ff94
```
